Added trigger and parsing for all factions.
tunderix/HerkkaKolkki pull request #2
Opened 2024-09-01 12:48 UTC by MossGnomeWiz

2024-09-01 12:51 UTC, tunderix commented on src/heroes/parseMethods/factions.ts
> +export const getallfactions = (): IFaction[] => {
Kamelikirjaimii: getAllFactions

2024-09-01 12:51 UTC, tunderix commented on src/heroes/parseMethods/factions.ts
> +    for (const [key, value] of Object.entries(factiondata[0].records)) {
Ja taaaaaas

2024-09-01 12:51 UTC, tunderix commented on src/heroes/parseMethods/factions.ts
> +const castle = getfaction('sod.faction.castle');
Esimerkkirivi, voi poistaa

2024-09-01 12:51 UTC, tunderix commented on src/heroes/types/IFaction.ts
> +    identifier: string;
Eli tänne tarvitaa nyt sit kaikki muukin data mukaan ku identifier...
untranslatedName, alignment, nativeTerrain.....

2024-09-02 07:10 UTC, tunderix requested changes

2024-09-02 07:10 UTC, tunderix commented on src/heroes/types/IFaction.ts
> +                    "id": "sod.faction.castle.warrior",
Näille warriorille ja magelle pitää sit tehdä oma interface. Eli siis jotain tämmöstä:
{
identifier: string;
alignment: string;
...
warriorClass: IHeroClass;
mageClass: IHeroClass;
}

2024-09-02 07:10 UTC, tunderix commented on src/heroes/parseMethods/factions.ts
>  const getAllFactionNames = (): string[] => {
Tää factionNames funkkari on waaaaanha, ja tuuurha... Tän voi poistaa tän funkkarin, liitty alku-kokeiluihi

2024-09-02 07:10 UTC, tunderix commented on src/heroes/types/IFaction.ts
> +
Tänne pitää tehdä sit myös käännetty versio tosta factionistä. Eli siis ajatuksena näin:
interface ITranslatedFaction {
faction: IFaction;
translatedName;
translatedDescription;
}

2024-09-02 13:34 UTC, MossGnomeWiz commented on src/heroes/parseMethods/factions.ts
> +export const getallfactions = (): IFaction[] => {
Korjattu tekstin luettavuus.

2024-09-02 13:34 UTC, MossGnomeWiz commented on src/heroes/parseMethods/factions.ts
> +    for (const [key, value] of Object.entries(factiondata[0].records)) {
Korjattu luettavuus.

2024-10-03 12:50 UTC, merged